"""add knowledge_base_id to conversations

Revision ID: 60f4ceb6e659
Revises: 8152825c758d
Create Date: 2026-09-21 21:50:26.547233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f4ceb6e659'
down_revision: Union[str, Sequence[str], None] = '8152825c758d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('knowledge_base_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_conversations_knowledge_base_id'), 'conversations', ['knowledge_base_id'], unique=False)
    op.create_foreign_key(op.f('fk_conversations_knowledge_base_id_knowledge_bases'), 'conversations', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_conversations_knowledge_base_id_knowledge_bases'), 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_knowledge_base_id'), table_name='conversations')
    op.drop_column('conversations', 'knowledge_base_id')
    # ### end Alembic commands ###
